name: Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        language: ['javascript']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
          
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
